In [102]:
import pandas as pd

# Data Acquisition

In [103]:
path = "../data/Resume.csv"

resume_df = pd.read_csv(path)

resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [104]:
resume_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   object
 2   Resume_html  2484 non-null   object
 3   Category     2484 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.8+ KB

In [105]:
path = "../data/training_data.csv"

job_df = pd.read_csv(path)

job_df.head()

,company_name,job_description,position_title,description_length,model_response
0,Google,minimum qualifications\r\nbachelors degree or ...,Sales Specialist,2727,"{\r\n ""Core Responsibilities"": ""Responsible ..."
1,Apple,description\r\nas an asc you will be highly in...,Apple Solutions Consultant,828,"{\r\n ""Core Responsibilities"": ""as an asc yo..."
2,Netflix,its an amazing time to be joining netflix as w...,Licensing Coordinator - Consumer Products,3205,"{\r\n ""Core Responsibilities"": ""Help drive b..."
3,Robert Half,description\r\n\r\nweb designers looking to ex...,Web Designer,2489,"{\r\n ""Core Responsibilities"": ""Designing we..."
4,TrackFive,at trackfive weve got big goals were on a miss...,Web Developer,3167,"{\r\n ""Core Responsibilities"": ""Build and la..."

In [106]:
job_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company_name        853 non-null    object
 1   job_description     853 non-null    object
 2   position_title      853 non-null    object
 3   description_length  853 non-null    int64
 4   model_response      853 non-null    object
dtypes: int64(1), object(4)
memory usage: 33.4+ KB

In [107]:
job_df['model_response'][1]

' {\r\n  "Core Responsibilities": "as an asc you will be highly influential in growing mind and market share of apple products while building longterm relationships with those who share your passion customer experiences are driven through you and your partner team growing in an ever changing and challenging environment you strive for perfection whether its maintaining visual merchandising or helping to grow and develop your partner team",\r\n  "Required Skills": "a passion to help people understand how apple products can enrich their livesexcellent communication skills allowing you to be as comfortable in front of a small group as you are speaking with individuals years preferred working in a dynamic sales andor results driven environment as well as proven success developing customer loyaltyability to encourage a partner team and grow apple business",\r\n  "Educational Requirements": "N/A",\r\n  "Experience Level": "years preferred",\r\n  "Preferred Qualifications": "N/A",\r\n  "Compensation and Benefits": "N/A"\r\n}'

# Data Cleaning

### Missing Values

In [108]:
cols_with_question = resume_df.columns[resume_df.isin(['?']).any()].tolist()
print(cols_with_question)

[]

In [109]:
cols_with_question = job_df.columns[job_df.isin(['?']).any()].tolist()
print(cols_with_question)

[]

In [110]:
print( (job_df.isna().sum() / len(job_df) ) * 100)

company_name          0.0
job_description       0.0
position_title        0.0
description_length    0.0
model_response        0.0
dtype: float64

In [111]:
print( (resume_df.isna().sum() / len(resume_df) ) * 100)

ID             0.0
Resume_str     0.0
Resume_html    0.0
Category       0.0
dtype: float64

### Duplicates

In [112]:
job_df.duplicated().sum()

np.int64(0)

In [113]:
resume_df.duplicated().sum()

np.int64(0)

## Data Preprocessing

### Text Cleaning
- remove html
- remove whitespace
- remove extra chars
- lowercase

In [114]:
from bs4 import BeautifulSoup
import re

def clean_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    text = BeautifulSoup(text, "html.parser").get_text(" ")
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^a-z0-9+#.\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [115]:
job_df["clean_description"] = job_df["job_description"].apply(clean_text)
resume_df["clean_description"] = resume_df["Resume_str"].apply(clean_text)

In [116]:
print(job_df["clean_description"], '\n')
print(resume_df["clean_description"])

0      minimum qualifications bachelors degree or equ...
1      description as an asc you will be highly influ...
2      its an amazing time to be joining netflix as w...
3      description web designers looking to expand yo...
4      at trackfive weve got big goals were on a miss...
                             ...
848    job description parttime make big money at men...
849    responsibilities parkers internship program wa...
850    the borgen project is an innovative national c...
851    put the world on vacation at wyndham destinati...
852    this job handles customer inquiries by telepho...
Name: clean_description, Length: 853, dtype: object

0       hr administrator marketing associate hr admini...
1       hr specialist us hr operations summary versati...
2       hr director summary over 20 years experience i...
3       hr specialist summary dedicated driven and dyn...
4       hr manager skill highlights hr skills hr depar...
                              ...
2479    rank sgt e 5 non commissioned officer in charg...
2480    government relations communications and organi...
2481    geek squad agent professional profile it suppo...
2482    program director office manager summary highly...
2483    storekeeper ii professional summary the purpos...
Name: clean_description, Length: 2484, dtype: object

### Keyword Extraction
- skills
- responsibilites
- qualifications
- requirements
- degree
- experience

#### Resume

In [136]:
resume_df["clean_description"][7]

'hr manager professional summary senior hr professional with a continuous improvement approach to building and supporting organizations. driven hr manager bringing an innovative approach to human resource management while creating a team driven environment that fosters room for development and growth. dedicated hr professional with strong grasp of employment laws compliance issues and benefits plans. successfully introduces process improvements and staff development initiatives to drive corporate goal attainment. creative business partner dedicated to developing unique employee orientation and training programs that will generate a loyal and knowledgeable staff. skills administrative adp backup benefits bookkeeping clarify competitive customer service database delivery documentation employee relations filing government hr human resources human resource insurance job analysis labor relations law enforcement team building letters market meetings mail office payroll processing payroll personnel policies processes project management proposal quality recruiting recruitment safety strategy employee handbooks vendor management vendor management vision year end work history hr manager 06 2016 to current company name city state developed and evolved the department s mission workflows and structure while continuously developing and improving processes in an ever changing environment. implemented the company s first sourcing tracking system. built a comprehensive employee recruiting strategy allowing me to fill 50+ positions in a period of 9 months. cut cost per hire and reduced average days to fill positions. achieved department goal by reducing turnover. placed new benefits broker and coordinated the implementation of new benefit programs ensuring they were current and competitive. educated and advised employees on group health plans voluntary benefits and 401 k retirement plans. managed all aspects of leave administration including employee notifications and vendor management disability programs and health benefits. developed new process for employee evaluation which resulted in marked performance improvements. handled understaffing disputes terminating employees and administering disciplinary procedures. resolved employment related disputes through proactive communication. offered fair and equitable compensation by comparing current salaries with market pay. audited workplace employee and management policies and procedures. developed and enforced company policy and procedures relating to all phases of human resources activity. sr. hr generalist 01 2015 to 05 2016 company name city state acted as a liaison and maintained open lines of communication between directors middle management and front line employees. developed company personnel policies standard operating procedures and employee handbooks. established and monitored employee pay scales. audited workplace employee and management policies and procedures. educated and advised employees on group health plans voluntary benefits and 401 k retirement plans. built a comprehensive employee recruiting strategy. managed the employee rewards programs. conducted job analysis and job evaluations resulting in quality job specifications. developed innovative new employee orientation programs including safety training. shadowed employees to determine an accurate description of the duties and skills required for each position. developed and enforced company policy and procedures relating to all phases of human resources activity. managed all aspects of leave administration including employee notifications and vendor management disability programs and health benefits. benefits administrator 01 2014 to 06 2014 company name city state closely partnering with brokers to minimize year over year cost increases for medical dental and vision health plans. organized district wide benefits fair. provided hands on customer service to 2500 district employees and retirees. educated and advised employees on group health plans voluntary benefits and retirement plans. human resources supervisor 08 2013 to 02 2014 company name city state led a comprehensive safety training for 55 staff members. handled understaffing disputes terminating employees and administering disciplinary procedures. resolved employment related disputes through proactive communication. coordinated work activities of subordinates and staff relating to employment compensation labor relations and employee relations. developed company personnel policies standard operating procedures and employee handbooks. developed and facilitated all new hire orientations. audited workplace employee and management policies and procedures. educated and advised employees on group health plans voluntary benefits and 401 k retirement plans. built a comprehensive employee recruiting strategy. developed innovative new employee orientation programs including safety training. acted as liaison between employees and insurance carriers to resolve problems and clarify benefits. human resources generalist administrative assistant 02 2013 to 08 2013 company name city state conducted background checks on candidates by obtaining information from law enforcement officials previous employers and references. evaluated timecards for accuracy on the regular and overtime hours. updated presentation documents for the compensation committee to review. captured key feedback from employees during exit interviews. supported human resources staff with new hire orientations and monthly departmental meetings. implemented a tracking database for employee professional development and licensure renewal credits. coordinated employment offers with management and extended offers to selected candidates. researched all payroll cobra disability and fmla issues. reviewed human resource paperwork for accuracy and completeness by verifying collecting and correcting additional data. managed all aspects of leave administration including employee notifications and vendor management disability programs and health benefits. developed company personnel policies standard operating procedures and employee handbooks. conducted employment verifications and investigations. built a comprehensive employee recruiting strategy. shadowed employees to determine an accurate description of the duties and skills required for each position. developed and enforced company policy and procedures relating to all phases of human resources activity. acted as liaison between employees and insurance carriers to resolve problems and clarify benefits. processed unemployment claims and acted as the company representative at unemployment hearings. human resources assistant 09 2008 to 02 2013 company name city state performed various administrative functions including filing paperwork delivering mail sorting mail office cleaning and bookkeeping. managed employee exit interviews and paperwork. provided backup payroll if needed. recruited and screened qualified potential employees. developed and facilitated all new hire orientations. conducted employment verifications and investigations. facilitated the criminal background check process for new hires. conducted background checks on candidates by obtaining information from law enforcement officials previous employers and references. supported human resources staff with new hire orientations and monthly departmental meetings. implemented a tracking database for employee professional development and licensure renewal credits. entered personnel and subcontractor data into a central database. coordinated and conducted new hire pre interviews. assisted management staff in annual year end processes and data audits. accurately prepared government compliance reports and proposal requests for employee data. addressed and resolved general payroll related inquires. sent notices to employees and subcontractors regarding expiring documentation. reviewed human resource paperwork for accuracy and completeness by verifying collecting and correcting additional data. completed employee employment verifications and unemployment paperwork in a timely manner. reviewed and corrected job offer letters for completeness and accuracy before approving their delivery. education bachelor of science business management 2009 university of phoenix san jose learning center city state business management mba 2010 university of phoenix city state mba human resources 2018 notre dame de namur university city state human resources'

In [118]:
def extract_degrees(text):
    if not isinstance(text, str):
        return []

    matches = re.findall(
        r"\b(?:high school diploma|associate(?:'s)?|bachelor(?:'s)?|master(?:'s)?|doctorate|ph\.?d\.?|mba)\b",
        text,
        flags=re.IGNORECASE
    )

    # dict for degrees
    degree_map = {
        "high school diploma": "High School Diploma",
        "associate": "Associate",
        "associate's": "Associate",
        "bachelor": "Bachelor",
        "bachelor's": "Bachelor",
        "master": "Master",
        "master's": "Master",
        "doctorate": "Doctorate",
        "phd": "Doctorate",
        "ph.d": "Doctorate",
        "ph.d.": "Doctorate",
        "mba": "MBA"
    }

    standardized = [
        degree_map.get(match.lower(), match.title())
        for match in matches
    ]

    return list(dict.fromkeys(standardized))

In [119]:
resume_df["degrees"] = resume_df["clean_description"].apply(extract_degrees)

In [120]:
resume_df["degrees"][0]

['Associate', 'High School Diploma']

#### Job

In [121]:
job_df["clean_description"][0]

'minimum qualifications bachelors degree or equivalent practical experience years of experience in saas or productivity tools businessexperience managing enterprise accounts with sales cycles preferred qualifications years of experience building strategic business partnerships with enterprise customersability to work through and with a reseller ecosystem to scale the businessability to plan pitch and execute a territory business strategyability to build relationships and to deliver results in a crossfunctionalmatrixed environmentability to identify crosspromoting and uppromoting opportunities within the existing account baseexcellent account management writtenverbal communication strategic and analyticalthinking skills about the job as a member of the google cloud team you inspire leading companies schools and government agencies to work smarter with google tools like google workspace search and chrome you advocate the innovative power of our products to make organizations more productive collaborative and mobile your guiding light is doing whats right for the customer you will meet customers exactly where they are at and provide them the best solutions for innovation using your passion for google products you help spread the magic of google to organizations around the world the google workspace team helps customers transform and evolve their business through the use of googles productivity collaboration and content management suite of applications as part of an entrepreneurial team in this growing business you will help shape the future of businesses use technology to connect with customers employees and partners as a google workspace sales specialist you will be responsible for maintenance and expansion of google workspace business growth across the region with customers in this role youll create and execute the strategy and provide unique insights on applying google workspace solutions to enterprisesyou will build an excellent pipeline and work with the account teams to build out the customer solution and establish partnerships you will strategize with partners to increase account and territory business growth you will work directly with customers coordinate internal resources and construct successful strategies at account and territory level google cloud accelerates organizations ability to digitally transform their business with the best infrastructure platform industry solutions and expertise we deliver enterprisegrade solutions that leverage googles cuttingedge technology all on the cleanest cloud in the industry customers in more than countries and territories turn to google cloud as their trusted partner to enable growth and solve their most critical business problems'

In [122]:
job_df['model_response'][0]

' {\r\n  "Core Responsibilities": "Responsible for expanding Google Workspace product adoption across an assigned territory. Build relationships with customers to understand needs and provide Google Workspace solutions. Partner with account teams to construct solutions and grow business for Google Workspace.",\r\n  "Required Skills": "Bachelor\'s degree or equivalent experience. Experience managing enterprise SaaS accounts and sales cycles.", \r\n  "Educational Requirements": "Bachelor\'s degree or equivalent experience.",\r\n  "Experience Level": "Experience managing enterprise SaaS accounts and sales cycles.",\r\n  "Preferred Qualifications": "Experience building strategic partnerships with enterprise customers. Ability to work through a reseller ecosystem. Excellent communication and strategic thinking skills.",\r\n  "Compensation and Benefits": "N/A"\r\n}'

In [123]:
import json

text = job_df['model_response'][0]
data = json.loads(text)

print(data["Core Responsibilities"])
print(data["Required Skills"])

Responsible for expanding Google Workspace product adoption across an assigned territory. Build relationships with customers to understand needs and provide Google Workspace solutions. Partner with account teams to construct solutions and grow business for Google Workspace.
Bachelor's degree or equivalent experience. Experience managing enterprise SaaS accounts and sales cycles.

In [124]:
parsed = job_df["model_response"].apply(json.loads)
parsed_df = pd.json_normalize(parsed)

job_df = job_df.join(parsed_df)

In [125]:
job_df["degrees"] = job_df["Educational Requirements"].apply(extract_degrees)

In [132]:
job_df["Educational Requirements"][:30]

0           Bachelor's degree or equivalent experience.
1                                                   N/A
2                                                   N/A
3                                                   N/A
4                                                   N/A
5                                                   N/A
6                                                   N/A
7                                                   N/A
8                                                   N/A
9           Bachelor's degree or equivalent experience.
10                                                  N/A
11          Bachelor's degree or equivalent experience.
12                                                  N/A
13    a bachelors degree in computer science, engine...
14                                                  N/A
15    Bachelor's degree in UI/UX or graphic design p...
16    Bachelor's degree required, MHA or MBA preferred.
17                                                  N/A
18    Master's degree in hospital administration, bu...
19                                                  N/A
20    Bachelor's degree in business or comparable ex...
21    Bachelor's degree in business, accounting or r...
22    Master's degree in business, health administra...
23    Bachelor's degree in healthcare related field ...
24                                                  N/A
25                                                  N/A
26                                                  N/A
27    Bachelor's degree in public relations, communi...
28    College degree required in relevant field of s...
29    Bachelor's degree or equivalent experience req...
Name: Educational Requirements, dtype: object

In [126]:
job_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   company_name               853 non-null    object
 1   job_description            853 non-null    object
 2   position_title             853 non-null    object
 3   description_length         853 non-null    int64
 4   model_response             853 non-null    object
 5   clean_description          853 non-null    object
 6   Core Responsibilities      853 non-null    object
 7   Required Skills            853 non-null    object
 8   Educational Requirements   853 non-null    object
 9   Experience Level           853 non-null    object
 10  Preferred Qualifications   853 non-null    object
 11  Compensation and Benefits  853 non-null    object
 12  medical specialty          1 non-null      object
 13  schedule                   1 non-null      object
 14  license/certification      1 non-null      object
 15  degrees                    853 non-null    object
dtypes: int64(1), object(15)
memory usage: 106.8+ KB

# Saving

In [127]:
resume_df.to_csv("../data/resume_clean.csv", index=False)
job_df.to_csv("../data/job_clean.csv", index=False)